gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - $(arg prefix)palm_finger_1_joint
     - $(arg prefix)palm_finger_2_joint
     - $(arg prefix)finger_middle_joint_1
     - $(arg prefix)finger_middle_joint_2
     - $(arg prefix)finger_middle_joint_3
     - $(arg prefix)finger_1_joint_1
     - $(arg prefix)finger_1_joint_2
     - $(arg prefix)finger_1_joint_3
     - $(arg prefix)finger_2_joint_1
     - $(arg prefix)finger_2_joint_2
     - $(arg prefix)finger_2_joint_3
     
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

joint_palm_finger_1_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)palm_finger_1_joint
joint_palm_finger_2_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)palm_finger_2_joint
  
  
joint_finger_middle_1_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_middle_joint_1
joint_finger_middle_2_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_middle_joint_2
joint_finger_middle_3_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_middle_joint_3
  
  
joint_finger_1_1_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_1_joint_1
joint_finger_1_2_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_1_joint_2
joint_finger_1_3_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_1_joint_3
  
joint_finger_2_1_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_2_joint_1
joint_finger_2_2_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_2_joint_2
joint_finger_2_3_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)finger_2_joint_3
  
robotiq_85_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)gripper_left_knuckle_joint

  