joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_left_wheel_joint
joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_right_wheel_joint
joint_frw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_right_wheel_joint
joint_flw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_left_wheel_joint

  
robotnik_base_control:
  type: rbeken_controller/RBEkenController
  joint:
    front_right_wheel_joint:
      name: $(arg prefix)front_right_wheel_joint
      max_speed: 27.27 # rad/s
    front_left_wheel_joint:
      name: $(arg prefix)front_left_wheel_joint
      max_speed: 27.27 # rad/s
    back_right_wheel_joint:
      name: $(arg prefix)back_right_wheel_joint
      max_speed: 27.27 # rad/s
    back_left_wheel_joint:
      name: $(arg prefix)back_left_wheel_joint
      max_speed: 27.27 # rad/s
  linear_speed_limit: 1.5 # m/s
  linear_acceleration_limit: 1.5 # m/s^2
  angular_speed_limit: 0.5 # rad/s
  angular_acceleration_limit: 1 # rad/s^2
  odom_frame: $(arg prefix)odom
  robot_base_frame: $(arg prefix)base_footprint
  odom_broadcast_tf: true
  odom_topic: 'robotnik_base_control/odom'
  wheel_base: 0.59
  track_width: 0.69
  wheel_diameter: 0.254
  cmd_watchdog_duration: 0.2
  imu_watchdog_duration: 0.1
  imu_topic: imu/data
  odom_publish_frequency: 100
  cmd_vel        : 'robotnik_base_control/cmd_vel'
  kinematic_mode : 'omni'
  motion_odometry: true
  in_motion_timer: 2.0


front_ptz_camera:
  joint_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: $(arg prefix)front_ptz_camera_pan_joint
  joint_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: $(arg prefix)front_ptz_camera_tilt_joint


robotnik_base_control_diff:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['$(arg prefix)front_left_wheel_joint','$(arg prefix)back_left_wheel_joint']
  right_wheel : ['$(arg prefix)front_right_wheel_joint','$(arg prefix)back_right_wheel_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.590 #ancho rueda+separacion entre ruedas (RB-Eken RUBBER)
  wheel_radius : 0.177 # (RB-Eken RUBBER)

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: $(arg prefix)base_footprint
  odom_frame_id: $(arg prefix)odom
  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 3.0 #1.5 # m/s
      min_velocity           : -3.0 #-1.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.00  # m/s^2
      min_acceleration       : -6.0 #-3.00 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.0 #3.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.0  # rad/s^2

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0
